### ISSUE TITLE
Document which Python version is required by gl3w?

### ISSUE THREAD

**Issue by tombsar** [skaslev/gl3w#18]
I couldn't find any information on the Github page to say which Python version is needed for gl3w (it looks to be Python 2.x). It would be good to have this documented somewhere obvious for people (like me) who know little about Python versions.

Since I installed Python 3.4 first, I thought I would modify gl3w_gen.py to make it work, rather than installing Python 2. I can submit these changes as a pull request, if there is a chance of them getting merged somehow.

**Comment by skaslev** [comment]
gl3w needs Python 2.x (2.6 or higher) to run. I would merge changes that make it work in Python 3, as long as gl3w still works in Python 2 too. E.g. having, |from __future__ import print_function|, switching all print statements to print calls, switching '%' operator to str.format, etc.

**Comment by tombsar** [comment]
> gl3w needs Python 2.x (2.6 or higher) to run.

This is important information which, as far as I can tell, is not documented anywhere. As far as this issue is concerned, all I'm asking for is a line in the README to this effect.

**Comment by skaslev** [comment]
Closing after #19 is merged.
