### ISSUE TITLE
Why do we need the extra gl3w layer, why not just use gl functions directly instead?

### ISSUE THREAD

**Issue by vexe** [skaslev/gl3w#26]
Greetings,

This is a question more than an issue. I was just wondering about something. In the generated code we have:

in gl3w.h
extern PFNGLACTIVESHADERPROGRAMPROC                         gl3wActiveShaderProgram;
...
#define glActiveShaderProgram                         gl3wActiveShaderProgram
...
in gl3w.c
PFNGLACTIVESHADERPROGRAMPROC                         gl3wActiveShaderProgram;

Why not just:
in gl3w.h
extern PFNGLACTIVESHADERPROGRAMPROC                         glActiveShaderProgram;

in gl3w.c
PFNGLACTIVESHADERPROGRAMPROC                         glActiveShaderProgram;

I did that and everything's still working. I'm not sure what is achieved by that extra layer.

**Comment by skaslev** [comment]
That's exactly how gl3w was working awhile back. It was causing crashes since the same symbols might be coming from another OpenGL library. I don't remember the details anymore at moment but having distinct symbol names and macros for renaming solved the issue.

**Comment by skaslev** [comment]
FYI this is the commit that introduced the gl3wFoo symbols and renaming https://github.com/skaslev/gl3w/commit/a443fde99c1e93fe5bac5e6af57f40791abbae8e

**Comment by Kos** [comment]
Hey, sorry for resurrecting, but if we had normal functions inside a namespace, wouldn't that elegantly solve the linker conflicts?

**Comment by tombsar** [comment]
@Kos I think it would, but namespaces are a C++ feature, and gl3w is currently written in C.
