### ISSUE TITLE
No S3TC/DXT compression enums

### ISSUE THREAD

**Issue by russelltg** [skaslev/gl3w#39]
I wanted to switch over to this, but I have one issue: there is no definition of `GL_COMPRESSED_RGBA_S3TC_DXT1_EXT` or similar. Is this by design? I see there is other compression formats like BPTC and ASTC, but no DXT.

**Comment by skaslev** [comment]
GL_COMPRESSED_RGBA_S3TC_DXT1_EXT is currently not present in [glcorearb.h](https://www.opengl.org/registry/api/GL/glcorearb.h) which is the API gl3w exports and loads.

**Comment by tombsar** [comment]
NB: The extension that provides these formats is described here: https://www.opengl.org/registry/specs/EXT/texture_compression_s3tc.txt

**Comment by skaslev** [comment]
To follow up, it seems that [glcorearb.h](https://www.khronos.org/registry/OpenGL/api/GL/glcorearb.h) is finally exposing `GL_COMPRESSED_RGBA_S3TC_DXT1_EXT` these days.
