### ISSUE TITLE
Phyton 2.7.3 error

### ISSUE THREAD

**Issue by sonoro1234** [skaslev/gl3w#41]
Downloading glcorearb.h to include/GL...
Traceback (most recent call last):
  File "C:\luaGL\gl3w-master\gl3w_gen.py", line 84, in <module>
    context = ssl._create_unverified_context()
AttributeError: 'module' object has no attribute '_create_unverified_context'

**Comment by skaslev** [comment]
Thanks for the report. It seems that ` _create_unverified_context` appeared first in Python 2.7.9.

Until a fix has landed you can use a newer Python version as a workaround.
