### ISSUE TITLE
some errors when using gl3w , help!!!

### ISSUE THREAD

**Issue by lugui2009** [skaslev/gl3w#54]
when I using the gl3w , I encountered these errors.Someone can help me .Thank you very much.
![gl3w](https://user-images.githubusercontent.com/20158014/34515103-91076c84-f0ab-11e7-9bb6-e8dd0cb37e73.jpg)

**Comment by skaslev** [comment]
Those are defined in `glcorearb.h` header which lives right besides `gl3w.h`.

How are you including `gl3w.h` header in your code? What's your include path while building? Also, can you paste the full (from the beginning) error output?

**Comment by tombsar** [comment]
It looks as though you have installed `gl3w.h` to the `/usr/include/GL/` directory. Did you also copy gl3w's version of `glcorearb.h` to that same location? These kinds of errors usually happen if the version of `glcorearb.h` used to generate `gl3w.h` is different from the one the compiler finds when trying to compile a program.

**Comment by lugui2009** [comment]
Thank you very much.That's it .@tombsar
